---
logLevel: info
MQTT_BROKER: "my-broker.localhost"
MQTT_PORT: 1234
MQTT_USER: "my-user"
MQTT_PASSWORD: "my-pwd"
HTTP_PORT: 5678
metrics:
  - name: electric_meter_total
    description: The total kWh measured by an electric meter
    type: counter
    topic: tele/electric_meter/SENSOR
    path: power.total
    labels:
      meter: power.meter
  - name: electric_meter_voltage
    description: The voltage measured
    type: gauge
    topic: tele/electric_meter/SENSOR
    path: power.voltage
    labels:
      meter: power.meter
  - name: electric_meter_current
    description: The electric current measured
    type: gauge
    topic: tele/electric_meter/SENSOR
    path: power.current
    labels:
      meter: power.meter

  - name: gas_meter_voltage
    description: The relay's voltage [V]
    type: gauge
    topic: tele/gas_meter/SENSOR
    path: voltage
  - name: gas_meter_counter
    description: measured amount of gas [1/100 m^3]
    type: counter
    topic: tele/gas_meter/SENSOR
    path: counter

  - name: gas_meter_wifi_fails
    description: Number of failed wifi connections
    type: counter
    topic: tele/gas_meter/SENSOR
    path: fails.wifi
  - name: gas_meter_mqtt_fails
    description: Number of failed connections to MQTT server
    type: counter
    topic: tele/gas_meter/SENSOR
    path: fails.mqtt

  - name: outside_temperature
    description: The current outside temperature [°C]
    type: gauge
    topic: tele/gas_meter/SENSOR
    path: temperature

  - name: gas_meter_voltage_2
    description: The relay's voltage [V]
    type: gauge
    topic: tele/gas_meter/2/SENSOR
    path: voltage
  - name: gas_meter_counter_2
    description: measured amount of gas [1/100 m^3]
    type: counter
    topic: tele/gas_meter/2/SENSOR
    path: counter

  - name: gas_meter_wifi_fails_2
    description: Number of failed wifi connections
    type: counter
    topic: tele/gas_meter/2/SENSOR
    path: fails.wifi
  - name: gas_meter_mqtt_fails_2
    description: Number of failed connections to MQTT server
    type: counter
    topic: tele/gas_meter/2/SENSOR
    path: fails.mqtt
