---
metrics:
  - name: electric_meter_total
    description: The total kWh measured by an electric meter
    type: counter
    topic: tele/tasmota_D9740F/SENSOR
    path: STROM.Total
    labels:
      meter: STROM.Meter_number
  - name: electric_meter_voltage
    description: The voltage measured
    type: gauge
    topic: tele/tasmota_D9740F/SENSOR
    path: STROM.voltage
    labels:
      meter: STROM.Meter_number
  - name: electric_meter_current
    description: The electric current measured
    type: gauge
    topic: tele/tasmota_D9740F/SENSOR
    path: STROM.current
    labels:
      meter: STROM.Meter_number
  
  - name: gas_meter_voltage
    description: The relay's voltage [V]
    type: gauge
    topic: tele/gas_meter/SENSOR
    path: voltage
  - name: gas_meter_counter
    description: measured amount of gas [1/100 m^3]
    type: counter
    topic: tele/gas_meter/SENSOR
    path: counter

  - name: gas_meter_wifi_fails
    description: Number of failed wifi connections
    type: counter
    topic: tele/gas_meter/SENSOR
    path: fails.wifi
  - name: gas_meter_mqtt_fails
    description: Number of failed connections to MQTT server
    type: counter
    topic: tele/gas_meter/SENSOR
    path: fails.mqtt

  - name: outside_temperature
    description: The current outside temperature [°C]
    type: gauge
    topic: tele/gas_meter/SENSOR
    path: temperature
