{
 "title": "Stromverbrauch",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Aktuelle Leistung",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "electric_meter_current{meter!=\"0\"} * electric_meter_voltage{meter!=\"0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Verbauch",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum by (label) (avg_over_time(electric_meter_current{meter!=\"0\"}[1m])*230)",
     "legendFormat": "Aktuell"
    },
    {
     "expr": "avg_over_time((electric_meter_voltage{meter!=\"0\"} * electric_meter_current{meter!=\"0\"})[1h:1m])",
     "legendFormat": "Durchschnittlich"
    }
   ]
  },
  {
   "title": "Zählerstand",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "electric_meter_total{meter!=\"0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kosten pro Tag",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "delta(electric_meter_total{meter!=\"0\"}[$__interval]) * 0.3",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Stromstärke",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "electric_meter_current{meter!=\"0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stromstärke",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 5, "y": 14 },
   "targets": [
    {
     "expr": "electric_meter_current{meter=\"70035089\"}",
     "legendFormat": "Stromstärke [A]"
    }
   ]
  },
  {
   "title": "Spannung",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "electric_meter_voltage{meter!=\"0\"}"
    }
   ]
  },
  {
   "title": "Spannung",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 5, "y": 20 },
   "targets": [
    {
     "expr": "electric_meter_voltage{meter!=\"0\"}",
     "legendFormat": "Spannung [V]"
    }
   ]
  }
 ]
}